[package]
name = "onedrive-api"
version = "0.9.0"
repository = "https://github.com/oxalica/onedrive-api"
license = "MIT"
categories = ["api-bindings"]
keywords = ["onedrive", "http", "api"]
description = "OneDrive HTTP REST API"
edition = "2018"
readme = "README.md"
documentation = "https://docs.rs/onedrive-api"

[features]
default = []
beta = []

[dependencies]
# Compat with `reqwest`
bytes = "1.0.1"
reqwest = { version = "0.11.0", default-features = false, features = [
    "json",
    "gzip",
    "rustls-tls",
] }
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
strum = { version = "0.24", features = ["derive"] }
thiserror = "1.0.15"
url = "2.2.0"

[package.metadata.docs.rs]
all-features = true

[workspace]
members = ["onedrive-api-test"]
